name: ta_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  firebase_core: 2.24.2
  firebase_auth: 4.15.3
  cloud_firestore: 4.13.6
  firebase_storage: 11.5.6
  nb_utils: 6.1.0
  google_sign_in: 6.2.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/bgLR.png
    - assets/bgLR.jpg
    - assets/icons/logo_login.png
    - assets/icons/google.png
  uses-material-design: true

